services:
  invoice-generator:
    image: ghcr.io/dvidbruhm/invoice-generator:latest
    environment:
      - DATABASE_URL=postgres://postgres@localhost:5432/invoices
      - JWT_SECRET=${INVOICE_GENERATOR_JWT_SECRET}
      - PORT=3000
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
