services:
  pdfding:
    image: mrmn/pdfding:latest
    restart: unless-stopped
    environment:
      - DEFAULT_THEME=dark
      - SECRET_KEY=${PDFDING_SECRET_KEY}
      - HOST_NAME=localhost
      - CSRF_COOKIE_SECURE=False
      - SESSION_COOKIE_SECURE=False
    volumes:
      - ${APP_DATA_DIR}/db:/home/nonroot/pdfding/db
      - ${APP_DATA_DIR}/media:/home/nonroot/pdfding/media
    x-runtipi:
      is_main: true
      internal_port: 8000

x-runtipi:
  schema_version: 2
